name: Pages

on: 
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  pwa:
      runs-on: ubuntu-latest
      steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Restore node modules cache
        uses: actions/cache@v3
        with:
          path: ./node_modules/
          key: npm-${{ hashFiles('package.json') }}
      -
        name: Install dependencies
        run: npm install
      -
        name: Build project
        run: ./node_modules/.bin/tsc
      -
        name: Setup Pages
        uses: actions/configure-pages@v3
      -
        name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: 'dist'
      -
        id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
